// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Server.Data;

#nullable disable

namespace Web_Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250327071546_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Server.Models.ApplyPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CVName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyPosts");
                });

            modelBuilder.Entity("Web_Server.Models.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("Web_Server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Công nghệ thông tin (IT)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chăm sóc sức khỏe & Y tế"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Giáo dục & Giảng dạy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kỹ thuật & Xây dựng"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tài chính & Kế toán"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bán hàng & Tiếp thị"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nhân sự (HR) & Tuyển dụng"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dịch vụ khách hàng & Hỗ trợ"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pháp lý & Tuân thủ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sáng tạo & Thiết kế"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sản xuất & Chế tạo"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Logistics & Chuỗi cung ứng"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bán lẻ & Thương mại điện tử"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Khách sạn & Du lịch"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Khoa học & Nghiên cứu"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Quan hệ công chúng (PR) & Truyền thông"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Công tác xã hội & Phi lợi nhuận"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bất động sản & Quản lý tài sản"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Truyền thông & Giải trí"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ô tô & Vận tải"
                        });
                });

            modelBuilder.Entity("Web_Server.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội, Việt Nam",
                            Description = "Công ty phần mềm hàng đầu Việt Nam",
                            Email = "contact@fpt.com",
                            Logo = "a",
                            Name = "FPT Software",
                            PhoneNumber = "024-73007300",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cần Thơ, Việt Nam",
                            Description = "Công ty dược phẩm lớn nhất Việt Nam",
                            Email = "info@dhgpharma.com",
                            Logo = "a",
                            Name = "DHG Pharma",
                            PhoneNumber = "0292-3891433",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hà Nội, Việt Nam",
                            Description = "Hệ thống giáo dục chất lượng cao",
                            Email = "info@vinschool.edu.vn",
                            Logo = "a",
                            Name = "Vinschool",
                            PhoneNumber = "024-39757483",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Address = "TP. Hồ Chí Minh, Việt Nam",
                            Description = "Công ty xây dựng hàng đầu Việt Nam",
                            Email = "contact@coteccons.vn",
                            Logo = "a",
                            Name = "Coteccons",
                            PhoneNumber = "028-38220800",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hà Nội, Việt Nam",
                            Description = "Ngân hàng thương mại hàng đầu",
                            Email = "support@mbbank.com.vn",
                            Logo = "a",
                            Name = "MB Bank",
                            PhoneNumber = "024-37674050",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "TP. Hồ Chí Minh, Việt Nam",
                            Description = "Nền tảng thương mại điện tử lớn",
                            Email = "support@tiki.vn",
                            Logo = "a",
                            Name = "Tiki",
                            PhoneNumber = "1900-6035",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Address = "TP. Hồ Chí Minh, Việt Nam",
                            Description = "Công ty logistics hàng đầu",
                            Email = "info@gemadept.com.vn",
                            Logo = "a",
                            Name = "Gemadept",
                            PhoneNumber = "028-39111333",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            Address = "Nha Trang, Việt Nam",
                            Description = "Chuỗi khách sạn và nghỉ dưỡng cao cấp",
                            Email = "info@vinpearl.com",
                            Logo = "a",
                            Name = "Vinpearl",
                            PhoneNumber = "1900-232389",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Address = "Hà Nội, Việt Nam",
                            Description = "Tập đoàn đa ngành lớn nhất Việt Nam",
                            Email = "contact@vingroup.net",
                            Logo = "a",
                            Name = "Vingroup",
                            PhoneNumber = "024-39749999",
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Address = "Hải Phòng, Việt Nam",
                            Description = "Hãng sản xuất ô tô hàng đầu Việt Nam",
                            Email = "support@vinfast.vn",
                            Logo = "a",
                            Name = "VinFast",
                            PhoneNumber = "1900-232389",
                            Status = 1,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Web_Server.Models.FollowCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("FollowCompanies");
                });

            modelBuilder.Entity("Web_Server.Models.FollowJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId");

                    b.HasIndex("UserId");

                    b.ToTable("FollowJobs");
                });

            modelBuilder.Entity("Web_Server.Models.Recruitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Recruitments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            CategoryId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lập trình viên Java",
                            Experience = "Senior",
                            Quantity = 5,
                            Rank = "A",
                            Salary = 25.0,
                            Status = 2,
                            Title = "Tuyển lập trình viên Java",
                            Type = "Full-time",
                            View = 150
                        },
                        new
                        {
                            Id = 2,
                            Address = "TP. HCM",
                            CategoryId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kỹ sư phần mềm",
                            Experience = "Mid",
                            Quantity = 3,
                            Rank = "B",
                            Salary = 30.0,
                            Status = 3,
                            Title = "Tuyển kỹ sư phần mềm",
                            Type = "Full-time",
                            View = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Đà Nẵng",
                            CategoryId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lập trình viên Fresher",
                            Experience = "Fresher",
                            Quantity = 10,
                            Rank = "C",
                            Salary = 12.0,
                            Status = 0,
                            Title = "Tuyển fresher lập trình",
                            Type = "Intern",
                            View = 50
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hà Nội",
                            CategoryId = 2,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bác sĩ đa khoa",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 35.0,
                            Status = 5,
                            Title = "Tuyển bác sĩ đa khoa",
                            Type = "Full-time",
                            View = 180
                        },
                        new
                        {
                            Id = 5,
                            Address = "TP. HCM",
                            CategoryId = 2,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Y tá điều dưỡng",
                            Experience = "Mid",
                            Quantity = 5,
                            Rank = "B",
                            Salary = 18.0,
                            Status = 2,
                            Title = "Tuyển y tá điều dưỡng",
                            Type = "Full-time",
                            View = 90
                        },
                        new
                        {
                            Id = 6,
                            Address = "Đà Nẵng",
                            CategoryId = 2,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kỹ thuật viên xét nghiệm",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 22.0,
                            Status = 3,
                            Title = "Tuyển kỹ thuật viên xét nghiệm",
                            Type = "Full-time",
                            View = 120
                        },
                        new
                        {
                            Id = 7,
                            Address = "Hà Nội",
                            CategoryId = 3,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giáo viên tiếng Anh",
                            Experience = "Senior",
                            Quantity = 3,
                            Rank = "A",
                            Salary = 30.0,
                            Status = 2,
                            Title = "Tuyển giáo viên tiếng Anh",
                            Type = "Full-time",
                            View = 220
                        },
                        new
                        {
                            Id = 8,
                            Address = "TP. HCM",
                            CategoryId = 3,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trợ giảng Toán",
                            Experience = "Junior",
                            Quantity = 4,
                            Rank = "C",
                            Salary = 15.0,
                            Status = 1,
                            Title = "Tuyển trợ giảng Toán",
                            Type = "Part-time",
                            View = 70
                        },
                        new
                        {
                            Id = 9,
                            Address = "Đà Nẵng",
                            CategoryId = 3,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giảng viên Đại học",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 40.0,
                            Status = 5,
                            Title = "Tuyển giảng viên đại học",
                            Type = "Full-time",
                            View = 3
                        },
                        new
                        {
                            Id = 10,
                            Address = "Hà Nội",
                            CategoryId = 4,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kỹ sư xây dựng",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 28.0,
                            Status = 3,
                            Title = "Tuyển kỹ sư xây dựng",
                            Type = "Full-time",
                            View = 175
                        },
                        new
                        {
                            Id = 11,
                            Address = "TP. HCM",
                            CategoryId = 4,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiến trúc sư",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 38.0,
                            Status = 4,
                            Title = "Tuyển kiến trúc sư",
                            Type = "Full-time",
                            View = 240
                        },
                        new
                        {
                            Id = 12,
                            Address = "Đà Nẵng",
                            CategoryId = 4,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kỹ thuật viên điện",
                            Experience = "Junior",
                            Quantity = 5,
                            Rank = "C",
                            Salary = 20.0,
                            Status = 2,
                            Title = "Tuyển kỹ thuật viên điện",
                            Type = "Full-time",
                            View = 95
                        },
                        new
                        {
                            Id = 13,
                            Address = "Hà Nội",
                            CategoryId = 5,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kế toán trưởng",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 45.0,
                            Status = 5,
                            Title = "Tuyển kế toán trưởng",
                            Type = "Full-time",
                            View = 260
                        },
                        new
                        {
                            Id = 14,
                            Address = "TP. HCM",
                            CategoryId = 5,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên viên tài chính",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 30.0,
                            Status = 3,
                            Title = "Tuyển chuyên viên tài chính",
                            Type = "Full-time",
                            View = 180
                        },
                        new
                        {
                            Id = 15,
                            Address = "Đà Nẵng",
                            CategoryId = 5,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhân viên thuế",
                            Experience = "Junior",
                            Quantity = 6,
                            Rank = "C",
                            Salary = 22.0,
                            Status = 2,
                            Title = "Tuyển nhân viên thuế",
                            Type = "Full-time",
                            View = 110
                        },
                        new
                        {
                            Id = 16,
                            Address = "Hà Nội",
                            CategoryId = 6,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên viên marketing",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 28.0,
                            Status = 3,
                            Title = "Tuyển chuyên viên marketing",
                            Type = "Full-time",
                            View = 150
                        },
                        new
                        {
                            Id = 17,
                            Address = "TP. HCM",
                            CategoryId = 6,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên gia SEO",
                            Experience = "Senior",
                            Quantity = 3,
                            Rank = "A",
                            Salary = 35.0,
                            Status = 2,
                            Title = "Tuyển chuyên gia SEO",
                            Type = "Full-time",
                            View = 2
                        },
                        new
                        {
                            Id = 18,
                            Address = "Đà Nẵng",
                            CategoryId = 6,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thực tập sinh marketing",
                            Experience = "Fresher",
                            Quantity = 6,
                            Rank = "C",
                            Salary = 12.0,
                            Status = 1,
                            Title = "Tuyển thực tập sinh marketing",
                            Type = "Intern",
                            View = 80
                        },
                        new
                        {
                            Id = 19,
                            Address = "Hà Nội",
                            CategoryId = 7,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chăm sóc khách hàng",
                            Experience = "Junior",
                            Quantity = 8,
                            Rank = "B",
                            Salary = 18.0,
                            Status = 2,
                            Title = "Tuyển nhân viên chăm sóc khách hàng",
                            Type = "Full-time",
                            View = 130
                        },
                        new
                        {
                            Id = 20,
                            Address = "TP. HCM",
                            CategoryId = 7,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhân viên telesales",
                            Experience = "Junior",
                            Quantity = 10,
                            Rank = "C",
                            Salary = 20.0,
                            Status = 3,
                            Title = "Tuyển nhân viên telesales",
                            Type = "Full-time",
                            View = 110
                        },
                        new
                        {
                            Id = 21,
                            Address = "Đà Nẵng",
                            CategoryId = 7,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trưởng nhóm CSKH",
                            Experience = "Mid",
                            Quantity = 3,
                            Rank = "A",
                            Salary = 28.0,
                            Status = 4,
                            Title = "Tuyển trưởng nhóm CSKH",
                            Type = "Full-time",
                            View = 170
                        },
                        new
                        {
                            Id = 22,
                            Address = "Hà Nội",
                            CategoryId = 8,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quản lý kho vận",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 40.0,
                            Status = 5,
                            Title = "Tuyển quản lý kho vận",
                            Type = "Full-time",
                            View = 250
                        },
                        new
                        {
                            Id = 23,
                            Address = "TP. HCM",
                            CategoryId = 8,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhân viên vận hành logistics",
                            Experience = "Mid",
                            Quantity = 6,
                            Rank = "B",
                            Salary = 30.0,
                            Status = 2,
                            Title = "Tuyển nhân viên vận hành logistics",
                            Type = "Full-time",
                            View = 180
                        },
                        new
                        {
                            Id = 24,
                            Address = "Đà Nẵng",
                            CategoryId = 8,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tài xế giao hàng",
                            Experience = "Junior",
                            Quantity = 10,
                            Rank = "C",
                            Salary = 22.0,
                            Status = 1,
                            Title = "Tuyển tài xế giao hàng",
                            Type = "Full-time",
                            View = 120
                        },
                        new
                        {
                            Id = 25,
                            Address = "Hà Nội",
                            CategoryId = 11,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên viên pháp lý",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 30.0,
                            Status = 3,
                            Title = "Tuyển chuyên viên pháp lý",
                            Type = "Full-time",
                            View = 90
                        },
                        new
                        {
                            Id = 26,
                            Address = "TP. HCM",
                            CategoryId = 11,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luật sư doanh nghiệp",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 50.0,
                            Status = 5,
                            Title = "Tuyển luật sư doanh nghiệp",
                            Type = "Full-time",
                            View = 110
                        },
                        new
                        {
                            Id = 27,
                            Address = "Đà Nẵng",
                            CategoryId = 11,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trợ lý luật sư",
                            Experience = "Junior",
                            Quantity = 6,
                            Rank = "C",
                            Salary = 22.0,
                            Status = 1,
                            Title = "Tuyển trợ lý luật sư",
                            Type = "Full-time",
                            View = 130
                        },
                        new
                        {
                            Id = 28,
                            Address = "Hà Nội",
                            CategoryId = 12,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thiết kế đồ họa",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 25.0,
                            Status = 2,
                            Title = "Tuyển thiết kế đồ họa",
                            Type = "Full-time",
                            View = 150
                        },
                        new
                        {
                            Id = 29,
                            Address = "TP. HCM",
                            CategoryId = 12,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "UI/UX Designer",
                            Experience = "Mid",
                            Quantity = 3,
                            Rank = "B",
                            Salary = 30.0,
                            Status = 3,
                            Title = "Tuyển UI/UX Designer",
                            Type = "Full-time",
                            View = 170
                        },
                        new
                        {
                            Id = 30,
                            Address = "Đà Nẵng",
                            CategoryId = 12,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thiết kế nội thất",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 28.0,
                            Status = 2,
                            Title = "Tuyển nhân viên thiết kế nội thất",
                            Type = "Full-time",
                            View = 190
                        },
                        new
                        {
                            Id = 31,
                            Address = "Hà Nội",
                            CategoryId = 13,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Công nhân sản xuất",
                            Experience = "Junior",
                            Quantity = 10,
                            Rank = "C",
                            Salary = 15.0,
                            Status = 1,
                            Title = "Tuyển công nhân sản xuất",
                            Type = "Full-time",
                            View = 210
                        },
                        new
                        {
                            Id = 32,
                            Address = "TP. HCM",
                            CategoryId = 13,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kỹ sư cơ khí",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 35.0,
                            Status = 3,
                            Title = "Tuyển kỹ sư cơ khí",
                            Type = "Full-time",
                            View = 230
                        },
                        new
                        {
                            Id = 33,
                            Address = "Đà Nẵng",
                            CategoryId = 13,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giám sát sản xuất",
                            Experience = "Senior",
                            Quantity = 3,
                            Rank = "A",
                            Salary = 40.0,
                            Status = 4,
                            Title = "Tuyển giám sát sản xuất",
                            Type = "Full-time",
                            View = 250
                        },
                        new
                        {
                            Id = 34,
                            Address = "Hà Nội",
                            CategoryId = 15,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhân viên bán hàng online",
                            Experience = "Junior",
                            Quantity = 6,
                            Rank = "C",
                            Salary = 14.0,
                            Status = 1,
                            Title = "Tuyển nhân viên bán hàng online",
                            Type = "Full-time",
                            View = 30
                        },
                        new
                        {
                            Id = 35,
                            Address = "TP. HCM",
                            CategoryId = 15,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quản lý cửa hàng",
                            Experience = "Mid",
                            Quantity = 3,
                            Rank = "B",
                            Salary = 28.0,
                            Status = 3,
                            Title = "Tuyển quản lý cửa hàng",
                            Type = "Full-time",
                            View = 50
                        },
                        new
                        {
                            Id = 36,
                            Address = "Đà Nẵng",
                            CategoryId = 15,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên viên TMĐT",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 30.0,
                            Status = 2,
                            Title = "Tuyển chuyên viên TMĐT",
                            Type = "Full-time",
                            View = 70
                        },
                        new
                        {
                            Id = 37,
                            Address = "Hà Nội",
                            CategoryId = 16,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lễ tân khách sạn",
                            Experience = "Junior",
                            Quantity = 5,
                            Rank = "C",
                            Salary = 16.0,
                            Status = 1,
                            Title = "Tuyển lễ tân khách sạn",
                            Type = "Full-time",
                            View = 90
                        },
                        new
                        {
                            Id = 38,
                            Address = "TP. HCM",
                            CategoryId = 16,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quản lý khách sạn",
                            Experience = "Senior",
                            Quantity = 2,
                            Rank = "A",
                            Salary = 45.0,
                            Status = 5,
                            Title = "Tuyển quản lý khách sạn",
                            Type = "Full-time",
                            View = 110
                        },
                        new
                        {
                            Id = 39,
                            Address = "Đà Nẵng",
                            CategoryId = 16,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hướng dẫn viên du lịch",
                            Experience = "Mid",
                            Quantity = 4,
                            Rank = "B",
                            Salary = 22.0,
                            Status = 2,
                            Title = "Tuyển hướng dẫn viên du lịch",
                            Type = "Full-time",
                            View = 130
                        });
                });

            modelBuilder.Entity("Web_Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Candidate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recruiter"
                        });
                });

            modelBuilder.Entity("Web_Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            CVId = 1,
                            Description = "A software developer",
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            Image = "alice.jpg",
                            Password = "pass123",
                            PhoneNumber = "0123456789",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            CVId = 2,
                            Description = "A data analyst",
                            Email = "bob@example.com",
                            FullName = "Bob Smith",
                            Image = "bob.jpg",
                            Password = "pass456",
                            PhoneNumber = "0987654321",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            CVId = 3,
                            Description = "A project manager",
                            Email = "charlie@example.com",
                            FullName = "Charlie Brown",
                            Image = "charlie.jpg",
                            Password = "pass789",
                            PhoneNumber = "0112233445",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Pine St",
                            CVId = 4,
                            Description = "A system admin",
                            Email = "david@example.com",
                            FullName = "David Lee",
                            Image = "david.jpg",
                            Password = "pass101",
                            PhoneNumber = "0223344556",
                            RoleId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Maple St",
                            CVId = 5,
                            Description = "A marketing specialist",
                            Email = "emma@example.com",
                            FullName = "Emma Watson",
                            Image = "emma.jpg",
                            Password = "pass202",
                            PhoneNumber = "0334455667",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Birch St",
                            CVId = 6,
                            Description = "A financial advisor",
                            Email = "frank@example.com",
                            FullName = "Frank Miller",
                            Image = "frank.jpg",
                            Password = "pass303",
                            PhoneNumber = "0445566778",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "159 Cedar St",
                            CVId = 7,
                            Description = "A UI/UX designer",
                            Email = "grace@example.com",
                            FullName = "Grace Davis",
                            Image = "grace.jpg",
                            Password = "pass404",
                            PhoneNumber = "0556677889",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "753 Walnut St",
                            CVId = 8,
                            Description = "A content writer",
                            Email = "henry@example.com",
                            FullName = "Henry Wilson",
                            Image = "henry.jpg",
                            Password = "pass505",
                            PhoneNumber = "0667788990",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "852 Fir St",
                            CVId = 9,
                            Description = "A HR manager",
                            Email = "isabella@example.com",
                            FullName = "Isabella Thomas",
                            Image = "isabella.jpg",
                            Password = "pass606",
                            PhoneNumber = "0778899001",
                            RoleId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "951 Palm St",
                            CVId = 10,
                            Description = "A sales executive",
                            Email = "jack@example.com",
                            FullName = "Jack Martinez",
                            Image = "jack.jpg",
                            Password = "pass707",
                            PhoneNumber = "0889900112",
                            RoleId = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Web_Server.Models.ApplyPost", b =>
                {
                    b.HasOne("Web_Server.Models.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recruitment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Server.Models.CV", b =>
                {
                    b.HasOne("Web_Server.Models.User", "User")
                        .WithOne("CV")
                        .HasForeignKey("Web_Server.Models.CV", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Server.Models.Company", b =>
                {
                    b.HasOne("Web_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Server.Models.FollowCompany", b =>
                {
                    b.HasOne("Web_Server.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Web_Server.Models.User", "User")
                        .WithMany("FollowCompany")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Server.Models.FollowJob", b =>
                {
                    b.HasOne("Web_Server.Models.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Server.Models.User", "User")
                        .WithMany("FollowJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recruitment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Server.Models.Recruitment", b =>
                {
                    b.HasOne("Web_Server.Models.Category", "Category")
                        .WithMany("Recruitments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Server.Models.Company", "Company")
                        .WithMany("Recruitments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Server.Models.User", null)
                        .WithMany("Recruitments")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Web_Server.Models.User", b =>
                {
                    b.HasOne("Web_Server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Web_Server.Models.Category", b =>
                {
                    b.Navigation("Recruitments");
                });

            modelBuilder.Entity("Web_Server.Models.Company", b =>
                {
                    b.Navigation("Recruitments");
                });

            modelBuilder.Entity("Web_Server.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Web_Server.Models.User", b =>
                {
                    b.Navigation("CV")
                        .IsRequired();

                    b.Navigation("FollowCompany");

                    b.Navigation("FollowJobs");

                    b.Navigation("Recruitments");
                });
#pragma warning restore 612, 618
        }
    }
}
